create Database PruebaTecnica

--go
DROP DATABASE PruebaTecnica
use PruebaTecnica 
go


CREATE TABLE REG_SOLICITUDES_INGRESO (
ID_SOLICITUD INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
DOCUMENTO VARCHAR (20) NOT NULL,
APELLIDOS VARCHAR(60) NOT NULL,
NOMBRE VARCHAR (60)
);
INSERT INTO REG_SOLICITUDES_INGRESO ( DOCUMENTO, APELLIDOS, NOMBRE)
VALUES ('1010247985','CRuz','Gilberth');
INSERT INTO REG_SOLICITUDES_INGRESO ( DOCUMENTO, APELLIDOS, NOMBRE)
VALUES ('1234567891','Gonzalez','Camilo');

CREATE TABLE NOM_CONCEPTOS_NOMINA (
ID_CONCEPTO INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
DESC_CONCEPTO VARCHAR(60) NOT NULL,
COD_CONCEPTO VARCHAR(60) NOT NULL
);
INSERT INTO NOM_CONCEPTOS_NOMINA ( DESC_CONCEPTO, COD_CONCEPTO)
VALUES ('Recargo Nocturno','1');
INSERT INTO NOM_CONCEPTOS_NOMINA ( DESC_CONCEPTO, COD_CONCEPTO)
VALUES ('Recargo Festivo','2');


CREATE TABLE NOM_EMPLEADOS (
ID_EMPLEADO INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
ID_SOLICITUD INT NOT NULL
CONSTRAINT FK_SOLICITUD FOREIGN KEY (ID_SOLICITUD) REFERENCES REG_SOLICITUDES_INGRESO (ID_SOLICITUD)
);
INSERT INTO NOM_EMPLEADOS ( ID_SOLICITUD)
VALUES (1);
INSERT INTO NOM_EMPLEADOS ( ID_SOLICITUD)
VALUES (2);


-- APESAR DE QUE LA SIGUIENTE PENDE DE LAS 2 ANTERIORES, EL NOMBRE NO SE ENCUENTRA NORMALIZADO, YA QUE LAS DEMAS
-- TABLAS QUE CONFORMAN LA BASE DE DATOS SE ENCUENTRAN EN MAYUZCULA EXCEPTO ESTA. 

CREATE TABLE NOM_NOMINA_DEFINITIVA (
REGISTRO INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
FCH_CRE DATETIME NOT NULL,
ID_CONCEPTO INT NOT NULL,
ID_EMPLEADO INT NOT NULL,
VAL_NOMINA INT NOT NULL,
CANTIDAD INT NOT NULL,
CONSTRAINT FK_CONCEPTO FOREIGN KEY (ID_CONCEPTO) REFERENCES NOM_CONCEPTOS_NOMINA (ID_CONCEPTO),
CONSTRAINT FK_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES NOM_EMPLEADOS (ID_EMPLEADO)
);
INSERT INTO NOM_NOMINA_DEFINITIVA ( FCH_CRE, ID_CONCEPTO,ID_EMPLEADO,VAL_NOMINA,CANTIDAD)
VALUES ('2021-05-11',1,1,23001,1);
INSERT INTO NOM_NOMINA_DEFINITIVA ( FCH_CRE, ID_CONCEPTO,ID_EMPLEADO,VAL_NOMINA,CANTIDAD)
VALUES ('2021-05-11',2,2,28001,1);



CREATE TABLE LOG_CONSULTA_NOM_NOMINA_DEFINITIVA (
ID_REGISTRO  INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
USUARIO VARCHAR (30) NOT NULL,
FECHA  datetime NOT NULL,
OPERACION  VARCHAR(10),
DESCRIPCION_DE_EVENTO VARCHAR(max) 
)

-- consulta para los 2 ultimos registros en la tabla NOM_NOMINA_DEFINITIVA
select top 2 REGISTRO,FCH_CRE from NOM_NOMINA_DEFINITIVA ORDER BY REGISTRO DESC

---------------------------------------------
----- CONSULA PARA SACAR DATOS ESPECIFICOS DE VARIAS TABLAS
select CON.COD_CONCEPTO,CON.DESC_CONCEPTO,NOM.ID_EMPLEADO,REG.DOCUMENTO,REG.APELLIDOS,REG.NOMBRE, 
DEF.VAL_NOMINA,DEF.CANTIDAD
from REG_SOLICITUDES_INGRESO REG
INNER JOIN NOM_EMPLEADOS NOM ON REG.ID_SOLICITUD = NOM.ID_SOLICITUD
INNER JOIN NOM_NOMINA_DEFINITIVA DEF ON DEF.ID_EMPLEADO = NOM.ID_EMPLEADO
INNER JOIN NOM_CONCEPTOS_NOMINA CON ON CON.ID_CONCEPTO = DEF.ID_CONCEPTO
WHERE NOM.ID_EMPLEADO = 1
---------------------------------------------------------



CREATE PROCEDURE USP_CONSULTA_NOMINA_POR_DOCUMENTO   
@DOC_IDENTIDAD VARCHAR(50),
@Evento NUMERIC (5) ,
@Usuario VARCHAR(50) = ADMIN,
@REGISTRO_NOM_NOMINA_DEFINITIVA NUMERIC(18) = NULL
AS   
	IF @Evento = 1
	BEGIN
	select DEF.REGISTRO,CON.COD_CONCEPTO,CON.DESC_CONCEPTO,NOM.ID_EMPLEADO,REG.DOCUMENTO,REG.APELLIDOS,REG.NOMBRE, 
	DEF.VAL_NOMINA,DEF.CANTIDAD
	from REG_SOLICITUDES_INGRESO REG
	INNER JOIN NOM_EMPLEADOS NOM ON REG.ID_SOLICITUD = NOM.ID_SOLICITUD
	INNER JOIN NOM_NOMINA_DEFINITIVA DEF ON DEF.ID_EMPLEADO = NOM.ID_EMPLEADO
	INNER JOIN NOM_CONCEPTOS_NOMINA CON ON CON.ID_CONCEPTO = DEF.ID_CONCEPTO
	WHERE REG.DOCUMENTO = @DOC_IDENTIDAD
	END

	IF @Evento = 2
	BEGIN

	UPDATE CON SET CON.DESC_CONCEPTO = @REGISTRO_NOM_NOMINA_DEFINITIVA from 
	NOM_CONCEPTOS_NOMINA CON INNER JOIN NOM_NOMINA_DEFINITIVA DEF ON DEF.ID_CONCEPTO = CON.ID_CONCEPTO
	INNER JOIN NOM_EMPLEADOS NOM ON NOM.ID_EMPLEADO = DEF.ID_EMPLEADO
	INNER JOIN  REG_SOLICITUDES_INGRESO REG ON REG.ID_SOLICITUD = NOM.ID_SOLICITUD
	WHERE REG.DOCUMENTO= @DOC_IDENTIDAD


	END

	IF @Evento = 3
	BEGIN
	DELETE FROM REG_SOLICITUDES_INGRESO WHERE DOCUMENTO = @DOC_IDENTIDAD
	END
GO  
